# Generated by Django 4.1.7 on 2023-03-21 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='college',
            new_name='university',
        ),
    ]
